
CREATE TABLE "motion_comment_section" (
    write_group_ids INTEGER[] ,
    meeting_id INTEGER NOT Null,
    submitter_can_write BOOLEAN ,
    comment_ids INTEGER[] ,
    weight INTEGER  DEFAULT 10000,
    sequential_number INTEGER NOT Null,
    read_group_ids INTEGER[] ,
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT Null
);

CREATE TABLE "option" (
    text TEXT ,
    no VARCHAR(255) ,
    abstain VARCHAR(255) ,
    content_object_id VARCHAR(255) ,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    weight INTEGER  DEFAULT 10000,
    yes VARCHAR(255) ,
    poll_id INTEGER ,
    used_as_global_option_in_poll_id INTEGER ,
    vote_ids INTEGER[] 
);

CREATE TABLE "projection" (
    content TEXT ,
    current_projector_id INTEGER ,
    history_projector_id INTEGER ,
    id INTEGER PRIMARY KEY,
    options TEXT ,
    stable BOOLEAN  DEFAULT false,
    weight INTEGER ,
    type VARCHAR(255) ,
    meeting_id INTEGER NOT Null,
    preview_projector_id INTEGER ,
    content_object_id VARCHAR(255) NOT Null
);

CREATE TABLE "projector_message" (
    id INTEGER PRIMARY KEY,
    message TEXT ,
    projection_ids INTEGER[] ,
    meeting_id INTEGER NOT Null
);

CREATE TABLE "organization_tag" (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT Null,
    color VARCHAR(255) NOT Null,
    tagged_ids TEXT[] ,
    organization_id INTEGER NOT Null
);

CREATE TABLE "personal_note" (
    id INTEGER PRIMARY KEY,
    note TEXT ,
    star BOOLEAN ,
    meeting_user_id INTEGER NOT Null,
    content_object_id VARCHAR(255) ,
    meeting_id INTEGER NOT Null
);

CREATE TABLE "motion_submitter" (
    weight INTEGER ,
    meeting_user_id INTEGER NOT Null,
    motion_id INTEGER NOT Null,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY
);

CREATE TABLE "mediafile" (
    is_directory BOOLEAN ,
    filesize INTEGER ,
    create_timestamp INTEGER ,
    access_group_ids INTEGER[] ,
    parent_id INTEGER ,
    owner_id VARCHAR(255) NOT Null,
    used_as_logo_pdf_header_l_in_meeting_id INTEGER ,
    used_as_font_bold_italic_in_meeting_id INTEGER ,
    id INTEGER PRIMARY KEY,
    pdf_information TEXT ,
    token VARCHAR(255) ,
    title VARCHAR(255) ,
    projection_ids INTEGER[] ,
    used_as_logo_projector_main_in_meeting_id INTEGER ,
    used_as_font_italic_in_meeting_id INTEGER ,
    used_as_font_monospace_in_meeting_id INTEGER ,
    used_as_font_projector_h1_in_meeting_id INTEGER ,
    used_as_logo_web_header_in_meeting_id INTEGER ,
    used_as_font_bold_in_meeting_id INTEGER ,
    is_public BOOLEAN NOT Null,
    used_as_logo_pdf_footer_l_in_meeting_id INTEGER ,
    child_ids INTEGER[] ,
    list_of_speakers_id INTEGER ,
    attachment_ids TEXT[] ,
    used_as_logo_projector_header_in_meeting_id INTEGER ,
    used_as_font_regular_in_meeting_id INTEGER ,
    used_as_font_chyron_speaker_name_in_meeting_id INTEGER ,
    inherited_access_group_ids INTEGER[] ,
    filename VARCHAR(255) ,
    mimetype VARCHAR(255) ,
    used_as_logo_pdf_header_r_in_meeting_id INTEGER ,
    used_as_logo_pdf_footer_r_in_meeting_id INTEGER ,
    used_as_logo_pdf_ballot_paper_in_meeting_id INTEGER ,
    used_as_font_projector_h2_in_meeting_id INTEGER 
);

CREATE TABLE "chat_message" (
    created INTEGER NOT Null,
    meeting_user_id INTEGER NOT Null,
    chat_group_id INTEGER NOT Null,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    content TEXT NOT Null
);

CREATE TABLE "agenda_item" (
    tag_ids INTEGER[] ,
    id INTEGER PRIMARY KEY,
    comment VARCHAR(255) ,
    duration INTEGER ,
    is_internal BOOLEAN ,
    level INTEGER ,
    item_number VARCHAR(255) ,
    content_object_id VARCHAR(255) NOT Null,
    child_ids INTEGER[] ,
    is_hidden BOOLEAN ,
    weight INTEGER  DEFAULT 10000,
    parent_id INTEGER ,
    meeting_id INTEGER NOT Null,
    closed BOOLEAN  DEFAULT false,
    type VARCHAR(255)  DEFAULT 'common',
    projection_ids INTEGER[] 
);

CREATE TABLE "speaker" (
    point_of_order BOOLEAN ,
    list_of_speakers_id INTEGER NOT Null,
    meeting_user_id INTEGER NOT Null,
    end_time INTEGER ,
    speech_state VARCHAR(255) ,
    note VARCHAR(255) ,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    begin_time INTEGER ,
    weight INTEGER  DEFAULT 10000
);

CREATE TABLE "motion_block" (
    agenda_item_id INTEGER ,
    meeting_id INTEGER NOT Null,
    title VARCHAR(255) NOT Null,
    sequential_number INTEGER NOT Null,
    motion_ids INTEGER[] ,
    list_of_speakers_id INTEGER NOT Null,
    projection_ids INTEGER[] ,
    id INTEGER PRIMARY KEY,
    internal BOOLEAN 
);

CREATE TABLE "action_worker" (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT Null,
    state VARCHAR(255) NOT Null,
    created INTEGER NOT Null,
    timestamp INTEGER NOT Null,
    result TEXT 
);

CREATE TABLE "group" (
    mediafile_inherited_access_group_ids INTEGER[] ,
    write_chat_group_ids INTEGER[] ,
    used_as_poll_default_id INTEGER ,
    used_as_motion_poll_default_id INTEGER ,
    used_as_assignment_poll_default_id INTEGER ,
    used_as_topic_poll_default_id INTEGER ,
    meeting_id INTEGER NOT Null,
    name VARCHAR(255) NOT Null,
    weight INTEGER ,
    default_group_for_meeting_id INTEGER ,
    read_comment_section_ids INTEGER[] ,
    id INTEGER PRIMARY KEY,
    read_chat_group_ids INTEGER[] ,
    poll_ids INTEGER[] ,
    write_comment_section_ids INTEGER[] ,
    permissions TEXT[] ,
    meeting_user_ids INTEGER[] ,
    admin_group_for_meeting_id INTEGER ,
    mediafile_access_group_ids INTEGER[] 
);

CREATE TABLE "topic" (
    id INTEGER PRIMARY KEY,
    sequential_number INTEGER NOT Null,
    attachment_ids INTEGER[] ,
    agenda_item_id INTEGER NOT Null,
    list_of_speakers_id INTEGER NOT Null,
    projection_ids INTEGER[] ,
    title VARCHAR(255) NOT Null,
    text TEXT ,
    tag_ids INTEGER[] ,
    poll_ids INTEGER[] ,
    meeting_id INTEGER NOT Null
);

CREATE TABLE "motion_workflow" (
    id INTEGER PRIMARY KEY,
    default_statute_amendment_workflow_meeting_id INTEGER ,
    meeting_id INTEGER NOT Null,
    name VARCHAR(255) NOT Null,
    sequential_number INTEGER NOT Null,
    state_ids INTEGER[] ,
    first_state_id INTEGER NOT Null,
    default_workflow_meeting_id INTEGER ,
    default_amendment_workflow_meeting_id INTEGER 
);

CREATE TABLE "projector" (
    chyron_background_color VARCHAR(255)  DEFAULT '#317796',
    show_title BOOLEAN  DEFAULT true,
    used_as_default_projector_for_mediafile_in_meeting_id INTEGER ,
    used_as_default_projector_for_motion_in_meeting_id INTEGER ,
    used_as_default_projector_for_motion_block_in_meeting_id INTEGER ,
    name VARCHAR(255) ,
    color VARCHAR(255)  DEFAULT '#000000',
    header_background_color VARCHAR(255)  DEFAULT '#317796',
    chyron_font_color VARCHAR(255)  DEFAULT '#ffffff',
    used_as_default_projector_for_topics_in_meeting_id INTEGER ,
    aspect_ratio_numerator INTEGER  DEFAULT 16,
    current_projection_ids INTEGER[] ,
    used_as_default_projector_for_projector_message_in_meeting_id INTEGER ,
    history_projection_ids INTEGER[] ,
    used_as_default_projector_for_current_list_of_speakers_in_meeting_id INTEGER ,
    used_as_default_projector_for_assignment_in_meeting_id INTEGER ,
    meeting_id INTEGER NOT Null,
    scroll INTEGER  DEFAULT 0,
    header_font_color VARCHAR(255)  DEFAULT '#f5f5f5',
    show_header_footer BOOLEAN  DEFAULT true,
    used_as_reference_projector_meeting_id INTEGER ,
    used_as_default_projector_for_motion_poll_in_meeting_id INTEGER ,
    show_clock BOOLEAN  DEFAULT true,
    sequential_number INTEGER NOT Null,
    preview_projection_ids INTEGER[] ,
    width INTEGER  DEFAULT 1200,
    aspect_ratio_denominator INTEGER  DEFAULT 9,
    background_color VARCHAR(255)  DEFAULT '#ffffff',
    header_h1_color VARCHAR(255)  DEFAULT '#317796',
    used_as_default_projector_for_assignment_poll_in_meeting_id INTEGER ,
    used_as_default_projector_for_amendment_in_meeting_id INTEGER ,
    used_as_default_projector_for_projector_countdowns_in_meeting_id INTEGER ,
    used_as_default_projector_for_poll_in_meeting_id INTEGER ,
    id INTEGER PRIMARY KEY,
    scale INTEGER  DEFAULT 0,
    show_logo BOOLEAN  DEFAULT true,
    used_as_default_projector_for_agenda_all_items_in_meeting_id INTEGER ,
    used_as_default_projector_for_list_of_speakers_in_meeting_id INTEGER 
);

CREATE TABLE "chat_group" (
    chat_message_ids INTEGER[] ,
    read_group_ids INTEGER[] ,
    write_group_ids INTEGER[] ,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT Null,
    weight INTEGER  DEFAULT 10000
);

CREATE TABLE "organization" (
    limit_of_meetings INTEGER  DEFAULT 0,
    active_meeting_ids INTEGER[] ,
    users_email_subject VARCHAR(255)  DEFAULT 'OpenSlides access data',
    name VARCHAR(255) ,
    legal_notice TEXT ,
    url VARCHAR(255)  DEFAULT 'https://example.com',
    enable_electronic_voting BOOLEAN ,
    committee_ids INTEGER[] ,
    default_language VARCHAR(255) NOT Null,
    archived_meeting_ids INTEGER[] ,
    theme_id INTEGER NOT Null,
    user_ids INTEGER[] ,
    users_email_replyto VARCHAR(255) ,
    reset_password_verbose_errors BOOLEAN ,
    limit_of_users INTEGER  DEFAULT 0,
    enable_chat BOOLEAN ,
    organization_tag_ids INTEGER[] ,
    mediafile_ids INTEGER[] ,
    users_email_body TEXT  DEFAULT 'Dear {name},\n\nthis is your personal OpenSlides login:\n\n{url}\nUsername: {username}\nPassword: {password}\n\n\nThis email was generated automatically.',
    privacy_policy TEXT ,
    login_text TEXT ,
    vote_decrypt_public_main_key VARCHAR(255) ,
    theme_ids INTEGER[] ,
    id INTEGER PRIMARY KEY,
    description TEXT ,
    template_meeting_ids INTEGER[] ,
    users_email_sender VARCHAR(255)  DEFAULT 'OpenSlides'
);

CREATE TABLE "motion" (
    title VARCHAR(255) NOT Null,
    amendment_ids INTEGER[] ,
    sort_child_ids INTEGER[] ,
    referenced_in_motion_state_extension_ids INTEGER[] ,
    id INTEGER PRIMARY KEY,
    number VARCHAR(255) ,
    lead_motion_id INTEGER ,
    state_extension_reference_ids TEXT[] ,
    supporter_meeting_user_ids INTEGER[] ,
    change_recommendation_ids INTEGER[] ,
    comment_ids INTEGER[] ,
    sequential_number INTEGER NOT Null,
    modified_final_version TEXT ,
    reason TEXT ,
    sort_weight INTEGER  DEFAULT 10000,
    sort_parent_id INTEGER ,
    all_origin_ids INTEGER[] ,
    recommendation_extension_reference_ids TEXT[] ,
    block_id INTEGER ,
    number_value INTEGER ,
    amendment_paragraph TEXT ,
    statute_paragraph_id INTEGER ,
    attachment_ids INTEGER[] ,
    meeting_id INTEGER NOT Null,
    poll_ids INTEGER[] ,
    option_ids INTEGER[] ,
    origin_meeting_id INTEGER ,
    all_derived_motion_ids INTEGER[] ,
    state_id INTEGER NOT Null,
    projection_ids INTEGER[] ,
    recommendation_extension VARCHAR(255) ,
    forwarded INTEGER ,
    category_id INTEGER ,
    agenda_item_id INTEGER ,
    origin_id INTEGER ,
    referenced_in_motion_recommendation_extension_ids INTEGER[] ,
    recommendation_id INTEGER ,
    list_of_speakers_id INTEGER NOT Null,
    personal_note_ids INTEGER[] ,
    start_line_number INTEGER  DEFAULT 1,
    derived_motion_ids INTEGER[] ,
    last_modified INTEGER ,
    state_extension VARCHAR(255) ,
    created INTEGER ,
    submitter_ids INTEGER[] ,
    tag_ids INTEGER[] ,
    text TEXT ,
    category_weight INTEGER  DEFAULT 10000
);

CREATE TABLE "motion_comment" (
    comment TEXT ,
    motion_id INTEGER NOT Null,
    section_id INTEGER NOT Null,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY
);

CREATE TABLE "motion_category" (
    meeting_id INTEGER NOT Null,
    weight INTEGER  DEFAULT 10000,
    level INTEGER ,
    child_ids INTEGER[] ,
    sequential_number INTEGER NOT Null,
    parent_id INTEGER ,
    motion_ids INTEGER[] ,
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT Null,
    prefix VARCHAR(255) 
);

CREATE TABLE "projector_countdown" (
    running BOOLEAN  DEFAULT false,
    used_as_poll_countdown_meeting_id INTEGER ,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    default_time INTEGER ,
    countdown_time REAL  DEFAULT 60,
    used_as_list_of_speakers_countdown_meeting_id INTEGER ,
    title VARCHAR(255) NOT Null,
    description VARCHAR(255)  DEFAULT '',
    projection_ids INTEGER[] 
);

CREATE TABLE "motion_change_recommendation" (
    line_to INTEGER ,
    text TEXT ,
    line_from INTEGER ,
    creation_time INTEGER ,
    motion_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    rejected BOOLEAN  DEFAULT false,
    internal BOOLEAN  DEFAULT false,
    type VARCHAR(255)  DEFAULT 'replacement',
    other_description VARCHAR(255) ,
    meeting_id INTEGER NOT Null
);

CREATE TABLE "motion_statute_paragraph" (
    motion_ids INTEGER[] ,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT Null,
    text TEXT ,
    weight INTEGER  DEFAULT 10000,
    sequential_number INTEGER NOT Null
);

CREATE TABLE "assignment" (
    title VARCHAR(255) NOT Null,
    open_posts INTEGER  DEFAULT 0,
    projection_ids INTEGER[] ,
    id INTEGER PRIMARY KEY,
    description TEXT ,
    phase VARCHAR(255)  DEFAULT 'search',
    default_poll_description TEXT ,
    sequential_number INTEGER NOT Null,
    poll_ids INTEGER[] ,
    agenda_item_id INTEGER ,
    number_poll_candidates BOOLEAN ,
    candidate_ids INTEGER[] ,
    list_of_speakers_id INTEGER NOT Null,
    tag_ids INTEGER[] ,
    attachment_ids INTEGER[] ,
    meeting_id INTEGER NOT Null
);

CREATE TABLE "poll_candidate_list" (
    id INTEGER PRIMARY KEY,
    poll_candidate_ids INTEGER[] ,
    meeting_id INTEGER NOT Null,
    option_id INTEGER NOT Null
);

CREATE TABLE "meeting_user" (
    motion_submitter_ids INTEGER[] ,
    vote_delegations_from_ids INTEGER[] ,
    number VARCHAR(255) ,
    structure_level VARCHAR(255) ,
    vote_weight VARCHAR(255) ,
    personal_note_ids INTEGER[] ,
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT Null,
    group_ids INTEGER[] ,
    comment TEXT ,
    about_me TEXT ,
    supported_motion_ids INTEGER[] ,
    vote_delegated_to_id INTEGER ,
    meeting_id INTEGER NOT Null,
    speaker_ids INTEGER[] ,
    assignment_candidate_ids INTEGER[] ,
    chat_message_ids INTEGER[] 
);

CREATE TABLE "theme" (
    warn_50 VARCHAR(255) ,
    primary_400 VARCHAR(255) ,
    warn_300 VARCHAR(255) ,
    primary_500 VARCHAR(255) NOT Null,
    primary_900 VARCHAR(255) ,
    accent_700 VARCHAR(255) ,
    accent_a700 VARCHAR(255) ,
    primary_50 VARCHAR(255) ,
    headbar VARCHAR(255) ,
    accent_300 VARCHAR(255) ,
    accent_400 VARCHAR(255) ,
    primary_200 VARCHAR(255) ,
    primary_800 VARCHAR(255) ,
    primary_a400 VARCHAR(255) ,
    warn_200 VARCHAR(255) ,
    warn_900 VARCHAR(255) ,
    accent_a100 VARCHAR(255) ,
    primary_100 VARCHAR(255) ,
    warn_100 VARCHAR(255) ,
    warn_a100 VARCHAR(255) ,
    warn_a400 VARCHAR(255) ,
    id INTEGER PRIMARY KEY,
    primary_a700 VARCHAR(255) ,
    primary_700 VARCHAR(255) ,
    primary_a100 VARCHAR(255) ,
    primary_a200 VARCHAR(255) ,
    warn_600 VARCHAR(255) ,
    warn_700 VARCHAR(255) ,
    warn_a700 VARCHAR(255) ,
    accent_500 VARCHAR(255) NOT Null,
    accent_600 VARCHAR(255) ,
    organization_id INTEGER NOT Null,
    yes VARCHAR(255) ,
    abstain VARCHAR(255) ,
    accent_50 VARCHAR(255) ,
    accent_800 VARCHAR(255) ,
    accent_900 VARCHAR(255) ,
    accent_a200 VARCHAR(255) ,
    accent_a400 VARCHAR(255) ,
    primary_300 VARCHAR(255) ,
    name VARCHAR(255) NOT Null,
    accent_100 VARCHAR(255) ,
    no VARCHAR(255) ,
    warn_400 VARCHAR(255) ,
    warn_500 VARCHAR(255) NOT Null,
    warn_800 VARCHAR(255) ,
    warn_a200 VARCHAR(255) ,
    theme_for_organization_id INTEGER ,
    accent_200 VARCHAR(255) ,
    primary_600 VARCHAR(255) 
);

CREATE TABLE "tag" (
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT Null,
    tagged_ids TEXT[] 
);

CREATE TABLE "poll_candidate" (
    id INTEGER PRIMARY KEY,
    poll_candidate_list_id INTEGER NOT Null,
    user_id INTEGER NOT Null,
    weight INTEGER NOT Null,
    meeting_id INTEGER NOT Null
);

CREATE TABLE "user" (
    poll_candidate_ids INTEGER[] ,
    meeting_ids INTEGER[] ,
    username VARCHAR(255) NOT Null,
    title VARCHAR(255) ,
    last_email_sent INTEGER ,
    organization_management_level VARCHAR(255) ,
    forwarding_committee_ids INTEGER[] ,
    poll_voted_ids INTEGER[] ,
    delegated_vote_ids INTEGER[] ,
    default_structure_level VARCHAR(255) ,
    is_present_in_meeting_ids INTEGER[] ,
    committee_ids INTEGER[] ,
    committee_management_ids INTEGER[] ,
    last_login INTEGER ,
    vote_ids INTEGER[] ,
    is_active BOOLEAN ,
    password VARCHAR(255) ,
    can_change_own_password BOOLEAN  DEFAULT true,
    default_vote_weight VARCHAR(255)  DEFAULT '1.000000',
    id INTEGER PRIMARY KEY,
    pronoun TEXT ,
    email VARCHAR(255) ,
    first_name VARCHAR(255) ,
    meeting_user_ids INTEGER[] ,
    default_number VARCHAR(255) ,
    is_physical_person BOOLEAN  DEFAULT true,
    is_demo_user BOOLEAN ,
    option_ids INTEGER[] ,
    organization_id INTEGER NOT Null,
    saml_id VARCHAR(255) ,
    last_name VARCHAR(255) ,
    default_password VARCHAR(255) ,
    gender VARCHAR(255) 
);

CREATE TABLE "vote" (
    option_id INTEGER NOT Null,
    user_id INTEGER ,
    delegated_user_id INTEGER ,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    weight VARCHAR(255) ,
    value VARCHAR(255) ,
    user_token VARCHAR(255) NOT Null
);

CREATE TABLE "assignment_candidate" (
    id INTEGER PRIMARY KEY,
    weight INTEGER  DEFAULT 10000,
    assignment_id INTEGER NOT Null,
    meeting_user_id INTEGER ,
    meeting_id INTEGER NOT Null
);

CREATE TABLE "motion_state" (
    weight INTEGER NOT Null,
    show_recommendation_extension_field BOOLEAN  DEFAULT false,
    merge_amendment_into_final VARCHAR(255)  DEFAULT 'undefined',
    submitter_withdraw_state_id INTEGER ,
    motion_recommendation_ids INTEGER[] ,
    workflow_id INTEGER NOT Null,
    name VARCHAR(255) NOT Null,
    allow_support BOOLEAN  DEFAULT false,
    show_state_extension_field BOOLEAN  DEFAULT false,
    allow_motion_forwarding BOOLEAN ,
    submitter_withdraw_back_ids INTEGER[] ,
    previous_state_ids INTEGER[] ,
    first_state_of_workflow_id INTEGER ,
    restrictions TEXT[]  DEFAULT '{}',
    allow_submitter_edit BOOLEAN  DEFAULT false,
    set_created_timestamp BOOLEAN ,
    next_state_ids INTEGER[] ,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    recommendation_label VARCHAR(255) ,
    css_class VARCHAR(255) NOT Null DEFAULT 'lightblue',
    allow_create_poll BOOLEAN  DEFAULT false,
    set_number BOOLEAN  DEFAULT true,
    motion_ids INTEGER[] 
);

CREATE TABLE "poll" (
    vote_count INTEGER ,
    sequential_number INTEGER NOT Null,
    option_ids INTEGER[] ,
    max_votes_per_option INTEGER  DEFAULT 1,
    crypt_signature VARCHAR(255) ,
    votes_signature VARCHAR(255) ,
    global_abstain BOOLEAN  DEFAULT false,
    description TEXT ,
    title VARCHAR(255) NOT Null,
    min_votes_amount INTEGER  DEFAULT 1,
    votes_raw TEXT ,
    id INTEGER PRIMARY KEY,
    onehundred_percent_base VARCHAR(255) NOT Null DEFAULT 'disabled',
    crypt_key VARCHAR(255) ,
    global_option_id INTEGER ,
    entitled_group_ids INTEGER[] ,
    projection_ids INTEGER[] ,
    state VARCHAR(255)  DEFAULT 'created',
    global_no BOOLEAN  DEFAULT false,
    votesvalid VARCHAR(255) ,
    meeting_id INTEGER NOT Null,
    pollmethod VARCHAR(255) NOT Null,
    votesinvalid VARCHAR(255) ,
    type VARCHAR(255) NOT Null,
    global_yes BOOLEAN  DEFAULT false,
    votescast VARCHAR(255) ,
    entitled_users_at_stop TEXT ,
    voted_ids INTEGER[] ,
    backend VARCHAR(255) NOT Null DEFAULT 'fast',
    max_votes_amount INTEGER  DEFAULT 1,
    content_object_id VARCHAR(255) NOT Null,
    is_pseudoanonymized BOOLEAN 
);

CREATE TABLE "committee" (
    organization_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT Null,
    description TEXT ,
    meeting_ids INTEGER[] ,
    forward_to_committee_ids INTEGER[] ,
    organization_tag_ids INTEGER[] ,
    default_meeting_id INTEGER ,
    user_ids INTEGER[] ,
    manager_ids INTEGER[] ,
    receive_forwardings_from_committee_ids INTEGER[] ,
    forwarding_user_id INTEGER 
);

CREATE TABLE "meeting" (
    motions_default_statute_amendment_workflow_id INTEGER NOT Null,
    users_email_replyto VARCHAR(255) ,
    assignment_poll_default_onehundred_percent_base VARCHAR(255)  DEFAULT 'valid',
    list_of_speakers_countdown_id INTEGER ,
    conference_open_microphone BOOLEAN  DEFAULT false,
    poll_default_group_ids INTEGER[] ,
    motions_default_sorting VARCHAR(255)  DEFAULT 'number',
    list_of_speakers_couple_countdown BOOLEAN  DEFAULT true,
    motions_export_follow_recommendation BOOLEAN  DEFAULT false,
    conference_los_restriction BOOLEAN  DEFAULT true,
    applause_timeout INTEGER  DEFAULT 5,
    export_pdf_page_margin_bottom INTEGER  DEFAULT 20,
    motions_amendments_prefix VARCHAR(255)  DEFAULT '-Ä',
    motion_poll_default_type VARCHAR(255)  DEFAULT 'pseudoanonymous',
    motion_submitter_ids INTEGER[] ,
    committee_id INTEGER NOT Null,
    conference_show BOOLEAN  DEFAULT false,
    motions_enable_reason_on_projector BOOLEAN  DEFAULT false,
    motions_default_workflow_id INTEGER NOT Null,
    motions_enable_sidebox_on_projector BOOLEAN  DEFAULT false,
    forwarded_motion_ids INTEGER[] ,
    admin_group_id INTEGER ,
    applause_type VARCHAR(255)  DEFAULT 'applause-type-bar',
    list_of_speakers_enable_pro_contra_speech BOOLEAN  DEFAULT false,
    conference_stream_poster_url VARCHAR(255) ,
    agenda_new_items_default_visibility VARCHAR(255)  DEFAULT 'internal',
    conference_auto_connect BOOLEAN  DEFAULT false,
    list_of_speakers_show_first_contribution BOOLEAN  DEFAULT false,
    users_pdf_welcometext TEXT  DEFAULT '[Place for your welcome and help text.]',
    organization_tag_ids INTEGER[] ,
    font_bold_id INTEGER ,
    motions_recommendation_text_mode VARCHAR(255)  DEFAULT 'diff',
    conference_enable_helpdesk BOOLEAN  DEFAULT false,
    agenda_show_subtitles BOOLEAN  DEFAULT false,
    motions_block_slide_columns INTEGER ,
    user_ids INTEGER[] ,
    default_projector_current_list_of_speakers_ids INTEGER[] NOT Null,
    motions_preamble TEXT  DEFAULT 'The assembly may decide:',
    motions_amendments_in_main_list BOOLEAN  DEFAULT true,
    poll_candidate_ids INTEGER[] ,
    projection_ids INTEGER[] ,
    default_projector_assignment_ids INTEGER[] NOT Null,
    assignment_poll_ballot_paper_selection VARCHAR(255)  DEFAULT 'CUSTOM_NUMBER',
    motions_supporters_min_amount INTEGER  DEFAULT 0,
    motion_poll_default_onehundred_percent_base VARCHAR(255)  DEFAULT 'YNA',
    users_enable_vote_delegations BOOLEAN ,
    list_of_speakers_show_amount_of_speakers_on_slide BOOLEAN  DEFAULT true,
    vote_ids INTEGER[] ,
    agenda_item_ids INTEGER[] ,
    present_user_ids INTEGER[] ,
    projector_countdown_default_time INTEGER NOT Null DEFAULT 60,
    motion_comment_ids INTEGER[] ,
    agenda_number_prefix VARCHAR(255) ,
    language VARCHAR(255) ,
    jitsi_room_name VARCHAR(255) ,
    conference_open_video BOOLEAN  DEFAULT false,
    motion_poll_default_group_ids INTEGER[] ,
    mediafile_ids INTEGER[] ,
    conference_auto_connect_next_speakers INTEGER  DEFAULT 0,
    motions_statute_recommendations_by VARCHAR(255) ,
    logo_projector_header_id INTEGER ,
    is_archived_in_organization_id INTEGER ,
    font_chyron_speaker_name_id INTEGER ,
    motions_line_length INTEGER  DEFAULT 85,
    speaker_ids INTEGER[] ,
    assignment_ids INTEGER[] ,
    list_of_speakers_enable_point_of_order_speakers BOOLEAN  DEFAULT true,
    users_pdf_welcometitle VARCHAR(255)  DEFAULT 'Welcome to OpenSlides',
    list_of_speakers_present_users_only BOOLEAN  DEFAULT false,
    motions_amendments_enabled BOOLEAN  DEFAULT true,
    poll_default_type VARCHAR(255)  DEFAULT 'analog',
    default_projector_motion_block_ids INTEGER[] NOT Null,
    default_projector_projector_message_ids INTEGER[] NOT Null,
    default_group_id INTEGER NOT Null,
    export_pdf_page_margin_left INTEGER  DEFAULT 20,
    poll_ballot_paper_selection VARCHAR(255) ,
    motions_show_referring_motions BOOLEAN  DEFAULT true,
    users_pdf_wlan_password VARCHAR(255) ,
    font_monospace_id INTEGER ,
    default_projector_list_of_speakers_ids INTEGER[] NOT Null,
    export_csv_encoding VARCHAR(255)  DEFAULT 'utf-8',
    topic_poll_default_group_ids INTEGER[] ,
    chat_group_ids INTEGER[] ,
    users_email_body TEXT  DEFAULT 'Dear {name},\n\nthis is your personal OpenSlides login:\n\n{url}\nUsername: {username}\nPassword: {password}\n\n\nThis email was generated automatically.',
    list_of_speakers_ids INTEGER[] ,
    applause_min_amount INTEGER  DEFAULT 1,
    logo_pdf_ballot_paper_id INTEGER ,
    applause_max_amount INTEGER  DEFAULT 0,
    projector_countdown_warning_time INTEGER NOT Null DEFAULT 0,
    export_pdf_fontsize INTEGER  DEFAULT 10,
    motion_poll_ballot_paper_selection VARCHAR(255)  DEFAULT 'CUSTOM_NUMBER',
    motions_amendments_of_amendments BOOLEAN  DEFAULT false,
    group_ids INTEGER[] ,
    export_pdf_pagenumber_alignment VARCHAR(255)  DEFAULT 'center',
    default_projector_mediafile_ids INTEGER[] NOT Null,
    font_bold_italic_id INTEGER ,
    motions_number_min_digits INTEGER  DEFAULT 2,
    motions_default_line_numbering VARCHAR(255)  DEFAULT 'outside',
    motions_show_sequential_number BOOLEAN  DEFAULT true,
    assignment_poll_enable_max_votes_per_option BOOLEAN  DEFAULT false,
    poll_sort_poll_result_by_votes BOOLEAN ,
    jitsi_room_password VARCHAR(255) ,
    users_email_subject VARCHAR(255)  DEFAULT 'OpenSlides access data',
    assignments_export_preamble TEXT ,
    assignment_poll_default_type VARCHAR(255)  DEFAULT 'pseudoanonymous',
    export_pdf_page_margin_top INTEGER  DEFAULT 25,
    projector_countdown_ids INTEGER[] ,
    motions_enable_text_on_projector BOOLEAN  DEFAULT true,
    motion_poll_default_backend VARCHAR(255)  DEFAULT 'fast',
    motion_block_ids INTEGER[] ,
    motion_state_ids INTEGER[] ,
    poll_ids INTEGER[] ,
    export_csv_separator VARCHAR(255)  DEFAULT ';',
    default_projector_motion_poll_ids INTEGER[] NOT Null,
    default_projector_poll_ids INTEGER[] NOT Null,
    users_email_sender VARCHAR(255)  DEFAULT 'OpenSlides',
    motion_comment_section_ids INTEGER[] ,
    motion_category_ids INTEGER[] ,
    assignment_candidate_ids INTEGER[] ,
    poll_default_method VARCHAR(255) ,
    motions_amendments_text_mode VARCHAR(255)  DEFAULT 'paragraph',
    users_pdf_wlan_encryption VARCHAR(255) ,
    is_active_in_organization_id INTEGER ,
    assignment_poll_ballot_paper_number INTEGER  DEFAULT 8,
    personal_note_ids INTEGER[] ,
    export_pdf_line_height REAL  DEFAULT 1.25,
    assignment_poll_default_backend VARCHAR(255)  DEFAULT 'fast',
    font_italic_id INTEGER ,
    font_projector_h2_id INTEGER ,
    motions_export_preamble TEXT ,
    custom_translations TEXT ,
    motions_statutes_enabled BOOLEAN  DEFAULT false,
    assignment_poll_default_group_ids INTEGER[] ,
    poll_default_onehundred_percent_base VARCHAR(255)  DEFAULT 'YNA',
    projector_ids INTEGER[] ,
    option_ids INTEGER[] ,
    template_for_organization_id INTEGER ,
    motions_export_title VARCHAR(255)  DEFAULT 'Motions',
    logo_pdf_header_l_id INTEGER ,
    end_time INTEGER ,
    location VARCHAR(255) ,
    imported_at INTEGER ,
    applause_show_level BOOLEAN  DEFAULT false,
    motions_export_submitter_recommendation BOOLEAN  DEFAULT true,
    description VARCHAR(255)  DEFAULT 'Presentation and assembly system',
    logo_pdf_footer_r_id INTEGER ,
    poll_ballot_paper_number INTEGER ,
    welcome_title VARCHAR(255)  DEFAULT 'Welcome to OpenSlides',
    list_of_speakers_initially_closed BOOLEAN  DEFAULT false,
    users_enable_vote_weight BOOLEAN  DEFAULT false,
    users_pdf_wlan_ssid VARCHAR(255) ,
    assignments_export_title VARCHAR(255)  DEFAULT 'Elections',
    default_meeting_for_committee_id INTEGER ,
    default_projector_amendment_ids INTEGER[] NOT Null,
    poll_default_backend VARCHAR(255)  DEFAULT 'fast',
    assignment_poll_default_method VARCHAR(255)  DEFAULT 'Y',
    list_of_speakers_can_set_contribution_self BOOLEAN  DEFAULT false,
    motion_statute_paragraph_ids INTEGER[] ,
    assignment_poll_add_candidates_to_list_of_speakers BOOLEAN  DEFAULT false,
    id INTEGER PRIMARY KEY,
    jitsi_domain VARCHAR(255) ,
    applause_enable BOOLEAN  DEFAULT false,
    motions_recommendations_by VARCHAR(255) ,
    users_allow_self_set_present BOOLEAN  DEFAULT true,
    list_of_speakers_amount_last_on_projector INTEGER  DEFAULT 0,
    motions_reason_required BOOLEAN  DEFAULT false,
    default_projector_agenda_all_items_ids INTEGER[] NOT Null,
    agenda_item_creation VARCHAR(255)  DEFAULT 'default_no',
    agenda_enable_numbering BOOLEAN  DEFAULT true,
    list_of_speakers_speaker_note_for_everyone BOOLEAN  DEFAULT true,
    chat_message_ids INTEGER[] ,
    conference_stream_url VARCHAR(255) ,
    poll_couple_countdown BOOLEAN  DEFAULT true,
    reference_projector_id INTEGER NOT Null,
    enable_anonymous BOOLEAN  DEFAULT false,
    motion_poll_ballot_paper_number INTEGER  DEFAULT 8,
    font_regular_id INTEGER ,
    projector_message_ids INTEGER[] ,
    logo_web_header_id INTEGER ,
    agenda_numeral_system VARCHAR(255)  DEFAULT 'arabic',
    list_of_speakers_amount_next_on_projector INTEGER  DEFAULT -1,
    topic_ids INTEGER[] ,
    motion_ids INTEGER[] ,
    motion_change_recommendation_ids INTEGER[] ,
    logo_pdf_header_r_id INTEGER ,
    font_projector_h1_id INTEGER ,
    poll_countdown_id INTEGER ,
    start_time INTEGER ,
    users_enable_presence_view BOOLEAN  DEFAULT false,
    welcome_text TEXT  DEFAULT 'Space for your welcome text.',
    export_pdf_pagesize VARCHAR(255)  DEFAULT 'A4',
    motions_amendments_multiple_paragraphs BOOLEAN  DEFAULT true,
    poll_candidate_list_ids INTEGER[] ,
    assignment_poll_sort_poll_result_by_votes BOOLEAN  DEFAULT true,
    tag_ids INTEGER[] ,
    default_projector_projector_countdowns_ids INTEGER[] NOT Null,
    motions_default_amendment_workflow_id INTEGER NOT Null,
    default_projector_motion_ids INTEGER[] NOT Null,
    export_pdf_page_margin_right INTEGER  DEFAULT 20,
    motions_enable_recommendation_on_projector BOOLEAN  DEFAULT true,
    motions_number_with_blank BOOLEAN  DEFAULT false,
    motion_workflow_ids INTEGER[] ,
    name VARCHAR(255)  DEFAULT 'OpenSlides',
    default_projector_topics_ids INTEGER[] NOT Null,
    default_projector_assignment_poll_ids INTEGER[] NOT Null,
    logo_projector_main_id INTEGER ,
    meeting_user_ids INTEGER[] ,
    all_projection_ids INTEGER[] ,
    applause_particle_image_url VARCHAR(255) ,
    agenda_show_internal_items_on_projector BOOLEAN  DEFAULT false,
    motions_number_type VARCHAR(255)  DEFAULT 'per_category',
    logo_pdf_footer_l_id INTEGER 
);

CREATE TABLE "list_of_speakers" (
    content_object_id VARCHAR(255) NOT Null,
    speaker_ids INTEGER[] ,
    projection_ids INTEGER[] ,
    meeting_id INTEGER NOT Null,
    id INTEGER PRIMARY KEY,
    closed BOOLEAN  DEFAULT false,
    sequential_number INTEGER NOT Null
);
