name: Autoupdate
on: [pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: go fmt
      run: test -z $(gofmt -l .)

    - name: go vet
      run: go vet ./...

    - name: test
      run: go test -timeout 10s -race ./...
